export default [
  {
    name: 'smile',
    src: '1',
    info: '微笑',
    value: '[微笑]',
    hover: '14@2x.gif',
  },
  {
    name: 'pout',
    src: '2',
    info: '撇嘴',
    value: '[撇嘴]',
    hover: '1@2x.gif',
  },
  {
    name: 'porn',
    src: '3',
    info: '色',
    value: '[色]',
    hover: '2@2x.gif',
  },
  {
    name: 'daze',
    src: '4',
    info: '发呆',
    value: '[发呆]',
    hover: '3@2x.gif',
  },
  {
    name: 'proud',
    src: '5',
    info: '得意',
    value: '[得意]',
    hover: '4@2x.gif',
  },
  {
    name: 'shedTears',
    src: '6',
    info: '流泪',
    value: '[流泪]',
    hover: '5@2x.gif',
  },
  {
    name: 'shy',
    src: '7',
    info: '害羞',
    value: '[害羞]',
    hover: '6@2x.gif',
  },
  {
    name: 'toShutUp',
    src: '8',
    info: '闭嘴',
    value: '[闭嘴]',
    hover: '7@2x.gif',
  },
  {
    name: 'sleep',
    src: '9',
    info: '睡',
    value: '[睡]',
    hover: '8@2x.gif',
  },
  {
    name: 'crying',
    src: '10',
    info: '大哭',
    value: '[大哭]',
    hover: '9@2x.gif',
  },
  {
    name: 'awkward',
    src: '11',
    info: '尴尬',
    value: '[尴尬]',
    hover: '10@2x.gif',
  },
  {
    name: 'rage',
    src: '12',
    info: '发怒',
    value: '[发怒]',
    hover: '11@2x.gif',
  },
  {
    name: 'naughty',
    src: '13',
    info: '调皮',
    value: '[调皮]',
    hover: '12@2x.gif',
  },
  {
    name: 'fangs',
    src: '14',
    info: '呲牙',
    value: '[呲牙]',
    hover: '13@2x.gif',
  },
  {
    name: 'confound',
    src: '15',
    info: '惊讶',
    value: '[惊讶]',
    hover: '14@2x.gif',
  },
  {
    name: 'sad',
    src: '16',
    info: '难过',
    value: '[难过]',
    hover: '15@2x.gif',
  },
  {
    name: 'cool',
    src: '17',
    info: '酷',
    value: '[酷]',
    hover: '16@2x.gif',
  },
  {
    name: 'coldSweat',
    src: '18',
    info: '冷汗',
    value: '[冷汗]',
    hover: '96@2x.gif',
  },
  {
    name: 'crazy',
    src: '19',
    info: '抓狂',
    value: '[抓狂]',
    hover: '18@2x.gif',
  },
  {
    name: 'spit',
    src: '20',
    info: '吐',
    value: '[吐]',
    hover: '19@2x.gif',
  },
  {
    name: 'snicker',
    src: '21',
    info: '偷笑',
    value: '[偷笑]',
    hover: '20@2x.gif',
  },
  {
    name: 'lovely',
    src: '22',
    info: '可爱',
    value: '[可爱]',
    hover: '21@2x.gif',
  },
  {
    name: 'eyes',
    src: '23',
    info: '白眼',
    value: '[白眼]',
    hover: '22@2x.gif',
  },
  {
    name: 'romantic',
    src: '24',
    info: '浪漫',
    value: '[浪漫]',
    hover: '23@2x.gif',
  },
  {
    name: 'hunger',
    src: '25',
    info: '饥饿',
    value: '[饥饿]',
    hover: '24@2x.gif',
  },
  {
    name: 'sleepy',
    src: '26',
    info: '困',
    value: '[困]',
    hover: '25@2x.gif',
  },
  {
    name: 'furious',
    src: '27',
    info: '惊恐',
    value: '[惊恐]',
    hover: '26@2x.gif',
  },
  {
    name: 'sweat',
    src: '28',
    info: '流汗',
    value: '[流汗]',
    hover: '27@2x.gif',
  },
  {
    name: 'sneer',
    src: '29',
    info: '憨笑',
    value: '[憨笑]',
    hover: '28@2x.gif',
  },
  {
    name: 'pretend',
    src: '30',
    info: '装逼',
    value: '[装逼]',
    hover: '29@2x.gif',
  },
  {
    name: 'struggle',
    src: '31',
    info: '奋斗',
    value: '[奋斗]',
    hover: '30@2x.gif',
  },
  {
    name: 'curse',
    src: '32',
    info: '咒骂',
    value: '[咒骂]',
    hover: '31@2x.gif',
  },
  {
    name: 'doubt',
    src: '33',
    info: '疑问',
    value: '[疑问]',
    hover: '32@2x.gif',
  },
  {
    name: 'hiss',
    src: '34',
    info: '嘘',
    value: '[嘘]',
    hover: '33@2x.gif',
  },
  {
    name: 'dizzy',
    src: '35',
    info: '晕',
    value: '[晕]',
    hover: '34@2x.gif',
  },
  {
    name: 'torment',
    src: '36',
    info: '折磨',
    value: '[折磨]',
    hover: '35@2x.gif',
  },
  {
    name: 'decay',
    src: '37',
    info: '衰',
    value: '[衰]',
    hover: '36@2x.gif',
  },
  {
    name: 'beat',
    src: '38',
    info: '敲打',
    value: '[敲打]',
    hover: '37@2x.gif',
  },
  {
    name: 'skull',
    src: '39',
    info: '骷髅',
    value: '[骷髅]',
    hover: '38@2x.gif',
  },
  {
    name: 'goodbye',
    src: '40',
    info: '再见',
    value: '[再见]',
    hover: '39@2x.gif',
  },
  {
    name: 'wipeSweat',
    src: '41',
    info: '擦汗',
    value: '[擦汗]',
    hover: '97@2x.gif',
  },
  {
    name: 'nosePicking',
    src: '42',
    info: '抠鼻',
    value: '[抠鼻]',
    hover: '98@2x.gif',
  },
  {
    name: 'applaud',
    src: '43',
    info: '鼓掌',
    value: '[鼓掌]',
    hover: '99@2x.gif',
  },
  {
    name: 'sniff',
    src: '44',
    info: '嗅大了',
    value: '[嗅大了]',
    hover: '100@2x.gif',
  },
  {
    name: 'smirk',
    src: '45',
    info: '坏笑',
    value: '[坏笑]',
    hover: '101@2x.gif',
  },
  {
    name: 'leftHum',
    src: '46',
    info: '左哼哼',
    value: '[左哼哼]',
    hover: '102@2x.gif',
  },
  {
    name: 'rightHum',
    src: '47',
    info: '右哼哼',
    value: '[右哼哼]',
    hover: '103@2x.gif',
  },
  {
    name: 'yawn',
    src: '48',
    info: '哈欠',
    value: '[哈欠]',
    hover: '104@2x.gif',
  },
  {
    name: 'despise',
    src: '49',
    info: '鄙视',
    value: '[鄙视]',
    hover: '105@2x.gif',
  },
  {
    name: 'grievance',
    src: '50',
    info: '委屈',
    value: '[委屈]',
    hover: '106@2x.gif',
  },
  {
    name: 'almostCrying',
    src: '51',
    info: '快哭了',
    value: '[快哭了]',
    hover: '107@2x.gif',
  },
  {
    name: 'shame',
    src: '52',
    info: '阴脸',
    value: '[阴脸]',
    hover: '108@2x.gif',
  },
  {
    name: 'kiss',
    src: '53',
    info: '亲亲',
    value: '[亲亲]',
    hover: '109@2x.gif',
  },
  {
    name: 'scare',
    src: '54',
    info: '吓',
    value: '[吓]',
    hover: '110@2x.gif',
  },
  {
    name: 'pitiful',
    src: '55',
    info: '可怜',
    value: '[可怜]',
    hover: '111@2x.gif',
  },

  {
    name: 'Chopper',
    src: '56',
    info: '菜刀',
    value: '[菜刀]',
    hover: '173@2x.gif',
  },
  {
    name: 'Watermelon',
    src: '57',
    info: '西瓜',
    value: '[西瓜]',
    hover: '174@2x.gif',
  },
  {
    name: 'beer',
    src: '58',
    info: '啤酒',
    value: '[啤酒]',
    hover: '212@2x.gif',
  },
  {
    name: 'basketball',
    src: '59',
    info: '篮球',
    value: '[篮球]',
    hover: '175@2x.gif',
  },
  {
    name: 'TableTennis',
    src: '60',
    info: '乒乓',
    value: '[乒乓]',
    hover: '178@2x.gif',
  },
  {
    name: 'coffee',
    src: '61',
    info: '咖啡',
    value: '[咖啡]',
    hover: '177@2x.gif',
  },
  {
    name: 'rice',
    src: '62',
    info: '米饭',
    value: '[米饭]',
    hover: '180@2x.gif',
  },
  {
    name: 'pigHead',
    src: '63',
    info: '猪头',
    value: '[猪头]',
    hover: '181@2x.gif',
  },
  {
    name: 'rose',
    src: '64',
    info: '玫瑰',
    value: '[玫瑰]',
    hover: '176@2x.gif',
  },
  {
    name: 'wither',
    src: '65',
    info: '凋谢',
    value: '[凋谢]',
    hover: '183@2x.gif',
  },
  {
    name: 'kiss',
    src: '66',
    info: '亲吻',
    value: '[亲吻]',
    hover: '173@2x.gif',
  },
  {
    name: 'heart',
    src: '67',
    info: '比心',
    value: '[比心]',
    hover: '174@2x.gif',
  },
  {
    name: 'heartBreak',
    src: '68',
    info: '心碎',
    value: '[心碎]',
    hover: '212@2x.gif',
  },
  {
    name: 'Birthday',
    src: '69',
    info: '生日',
    value: '[生日]',
    hover: '175@2x.gif',
  },
  {
    name: 'Lightning',
    src: '70',
    info: '闪电',
    value: '[闪电]',
    hover: '178@2x.gif',
  },
  {
    name: 'Bombs',
    src: '71',
    info: '炸弹',
    value: '[炸弹]',
    hover: '177@2x.gif',
  },
  {
    name: 'PocketKnife',
    src: '72',
    info: '小刀',
    value: '[小刀]',
    hover: '180@2x.gif',
  },
  {
    name: 'footBall',
    src: '73',
    info: '足球',
    value: '[足球]',
    hover: '181@2x.gif',
  },
  {
    name: 'Ladybug',
    src: '74',
    info: '瓢虫',
    value: '[瓢虫]',
    hover: '176@2x.gif',
  },
  {
    name: 'shit',
    src: '75',
    info: '便便',
    value: '[便便]',
    hover: '183@2x.gif',
  },
  {
    name: 'night',
    src: '76',
    info: '晚安',
    value: '[晚安]',
    hover: '173@2x.gif',
  },
  {
    name: 'sun',
    src: '77',
    info: '太阳',
    value: '[太阳]',
    hover: '174@2x.gif',
  },
  {
    name: 'gift',
    src: '78',
    info: '礼物',
    value: '[礼物]',
    hover: '212@2x.gif',
  },
  {
    name: 'huge',
    src: '79',
    info: '拥抱',
    value: '[拥抱]',
    hover: '175@2x.gif',
  },
  {
    name: 'Commendation',
    src: '80',
    info: '赞',
    value: '[赞]',
    hover: '178@2x.gif',
  },
  {
    name: 'despise',
    src: '81',
    info: '看不起',
    value: '[看不起]',
    hover: '177@2x.gif',
  },
  {
    name: 'Cooperation',
    src: '82',
    info: '合作',
    value: '[合作]',
    hover: '180@2x.gif',
  },
  {
    name: 'yeah',
    src: '83',
    info: '耶',
    value: '[耶]',
    hover: '181@2x.gif',
  },
  {
    name: 'baoQuan',
    src: '84',
    info: '抱拳',
    value: '[抱拳]',
    hover: '176@2x.gif',
  },
  {
    name: 'seduce',
    src: '85',
    info: '勾引',
    value: '[勾引]',
    hover: '183@2x.gif',
  },
  {
    name: 'raiseFist',
    src: '86',
    info: '举拳',
    value: '[举拳]',
    hover: '173@2x.gif',
  },
  {
    name: 'stigmatization',
    src: '87',
    info: '鄙视',
    value: '[鄙视]',
    hover: '174@2x.gif',
  },
  {
    name: 'rock',
    src: '88',
    info: '摇滚',
    value: '[摇滚]',
    hover: '212@2x.gif',
  },
  {
    name: 'Unbelief',
    src: '89',
    info: '不信',
    value: '[不信]',
    hover: '175@2x.gif',
  },
  {
    name: 'ok',
    src: '90',
    info: '明白',
    value: '[明白]',
    hover: '178@2x.gif',
  },
  {
    name: 'kiss',
    src: '91',
    info: '亲亲',
    value: '[亲亲]',
    hover: '177@2x.gif',
  },
  {
    name: 'miss',
    src: '92',
    info: '想你',
    value: '[想你]',
    hover: '180@2x.gif',
  },
  {
    name: 'happy',
    src: '93',
    info: '开心',
    value: '[开心]',
    hover: '181@2x.gif',
  },
  {
    name: 'shake',
    src: '94',
    info: '摇晃',
    value: '[摇晃]',
    hover: '176@2x.gif',
  },
  {
    name: 'scream',
    src: '95',
    info: '尖叫',
    value: '[尖叫]',
    hover: '183@2x.gif',
  },
];
